# Generated by Django 3.1.4 on 2022-04-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('caloriesPerLiter', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=200)),
                ('sugarGramsPerLiter', models.PositiveIntegerField()),
            ],
        ),
    ]
