# Generated by Django 3.1.4 on 2022-04-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerFridge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='sugarGramsPerLiter',
            new_name='alcoholPercentage',
        ),
    ]
